### ISSUE TITLE
Julia failed to build on 10.8.4

### ISSUE THREAD

**Issue by accopeland** [staticfloat/homebrew-julia#169]
Starting a couple of weeks ago, Julia builds began to fail with this error. 

./signals-unix.c:40:72: error: use of undeclared identifier 'ucontext64_t'; did you mean 'ucontext_t'?
    bt_size = rec_backtrace_ctx(bt_data, MAX_BT_SIZE, (bt_context_t)&((ucontext64_t*)context)->uc_mcontext64->__ss);
                                                                       ^
/usr/include/sys/_structs.h:227:26: note: 'ucontext_t' declared here
typedef _STRUCT_UCONTEXT        ucontext_t;     /* [???] user context */
                                ^
In file included from signal-handling.c:62:
./signals-unix.c:40:85: error: expected expression
    bt_size = rec_backtrace_ctx(bt_data, MAX_BT_SIZE, (bt_context_t)&((ucontext64_t*)context)->uc_mcontext64->__ss);
                                                                                    ^
2 errors generated.
make[1]: *** [signal-handling.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [julia-src-release] Error 2

I created gists of all make output and 'brew doctor'

https://gist.github.com/bf665a96f17af69d5b6c

https://gist.github.com/anonymous/395f9743bd10ffc00724

**Comment by accopeland** [comment]
I confirmed that I see the same error with a clone of the master julia repo. The fix for me was to change
'#include <machine/_structs.h>'  on line 12 of  src/signals-apple.c to '#include <sys/_structs.h>'

**Comment by staticfloat** [comment]
@accopeland I think you dropped a word in your solution; how did you fix this?

**Comment by accopeland** [comment]
Oh funny, all the important bits were markdown'ed out of existence.  The
comment should have said that I modified line 12 of src/signals-apple.c and
changed  #include <machine/_structs.h> to #include <sys/_structs.h>

Maybe I should have just supplied the git diff which I applied as a local
patch:

diff --git a/src/signals-apple.c b/src/signals-apple.c
index ab3709b..5001166 100644
--- a/src/signals-apple.c
+++ b/src/signals-apple.c
@@ -9,7 +9,7 @@
 #include <sys/_types/_ucontext64.h>
 #else
 #define __need_ucontext64_t
-#include <machine/_structs.h>
+#include <sys/_structs.h>
 #endif

 static mach_port_t segv_port = 0;



On Fri, Sep 11, 2015 at 10:27 AM, Elliot Saba <notifications@github.com>
wrote:

> @accopeland <https://github.com/accopeland> I think you dropped a word in
> your solution; how did you fix this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/staticfloat/homebrew-julia/issues/169#issuecomment-139606938>
> .
>



-- 

Alex Copeland
Joint Genome Institute, Walnut Creek, CA 94598
